# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1cf7088f543cc4f44c5affc43eb8fb1bbf0e972b239483e2cffcd47b7554d14a08c87b1adcadcb813f075acc557690ee9aa8edafd61556d9e52737134c11a45

test:
  secret_key_base: c5cf0e869260d327b05ca528ba274d9bb04b9a8fd21e2ffc57ca494b2aa5bcb31df9dedf5d05057571a9d7a0e978cbd8441f34db8145efd05b978e8a0a8e99d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
